
#spring.datasource.url=jdbc:mysql://localhost:3306/flutter_springboot?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#
#spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

#useSSL=false&allowMultiQueries=true&serverTimezone=UTC


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flutter_springboot?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  security:
#    user:
#      name: maiga
#      password: test
